# Generated by Django 3.0.5 on 2020-06-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Firstname', models.CharField(max_length=50)),
                ('Emp_Lastname', models.CharField(max_length=50)),
                ('Emp_Age', models.IntegerField()),
                ('Emp_Id', models.CharField(max_length=50)),
                ('Emp_Gender', models.CharField(max_length=10)),
                ('Emp_Email', models.EmailField(max_length=50)),
                ('Emp_Password', models.CharField(max_length=30)),
                ('Emp_Salary', models.FloatField()),
                ('Emp_Department', models.CharField(max_length=30)),
                ('Emp_phoneno', models.CharField(max_length=10)),
            ],
        ),
    ]
